language: fuse
os:
  - osx
compiler:
  - gcc
  - clang
sudo: required

cache:
  directories:
    - /Applications/Fuse.app
    - /usr/local/share/uno
    - $HOME/fuse

# http://stackoverflow.com/questions/27671854/travis-ci-fails-to-build-with-a-code-signing-error
# before_script:
#     - ./.travis/add-key.sh
install:
    - ./.travis/install.sh
script: ./.travis/test.sh
