language: fuse
os:
  - osx

sudo: required

cache:
  directories:
    - /Applications/Fuse.app
    - /usr/local/share/uno
    - $HOME/fuse

# before_script:
#     - ./.travis/add-key.sh
install:
    - ./.travis/install.sh
script: ./.travis/test.sh
