env:
  global:
    - NDK_VERSION=r10e
    - FUSE_VERSION=0.12.3.6348
    - UNOPROJ=TravisTest
language: objective-c
os:
  - osx
sudo: required

cache:
  directories:
    - /Applications/Fuse.app
    - /usr/local/share/uno
    - $HOME/fuse


before_install:
  - ./.travis/install-ndk.sh
  - ./.travis/install-fuse.sh

# http://stackoverflow.com/questions/27671854/travis-ci-fails-to-build-with-a-code-signing-error
# before_script:
#     - ./.travis/add-key.sh

script: ./.travis/test.sh
